# Generated by Django 4.2.25 on 2025-10-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_id', models.CharField(help_text='Unique identifier for the target', max_length=255, primary_key=True, serialize=False)),
                ('target_name', models.CharField(help_text='Name of the target', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_id', models.ForeignKey(help_text='Associated goal (exactly one goal per target)', on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Targets',
                'ordering': ['target_name'],
            },
        ),
    ]
