# Generated by Django 4.2.25 on 2025-10-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('projects', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date for this agenda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_1', models.ForeignKey(blank=True, help_text='Goal for target 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_1', to='goals.goal')),
                ('goal_2', models.ForeignKey(blank=True, help_text='Goal for target 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_2', to='goals.goal')),
                ('goal_3', models.ForeignKey(blank=True, help_text='Goal for target 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_3', to='goals.goal')),
                ('project_1', models.ForeignKey(blank=True, help_text='Project for target 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_1', to='projects.project')),
                ('project_2', models.ForeignKey(blank=True, help_text='Project for target 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_2', to='projects.project')),
                ('project_3', models.ForeignKey(blank=True, help_text='Project for target 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_3', to='projects.project')),
                ('target_1', models.ForeignKey(blank=True, help_text='Target 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_1', to='targets.target')),
                ('target_2', models.ForeignKey(blank=True, help_text='Target 2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_2', to='targets.target')),
                ('target_3', models.ForeignKey(blank=True, help_text='Target 3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_agendas_3', to='targets.target')),
            ],
            options={
                'verbose_name': 'Daily Agenda',
                'verbose_name_plural': 'Daily Agendas',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
