# Generated by Django 4.2.25 on 2025-10-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_fix_goal_id_datatype'),
        ('targets', '0002_dailyagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='goal_id',
            field=models.ForeignKey(blank=True, help_text='Associated goal (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
    ]
