# Generated by Django 4.2.25 on 2025-10-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_target_goal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyagenda',
            name='target_1_score',
            field=models.FloatField(blank=True, help_text='Score for target 1 (0, 0.5, or 1)', null=True),
        ),
        migrations.AddField(
            model_name='dailyagenda',
            name='target_2_score',
            field=models.FloatField(blank=True, help_text='Score for target 2 (0, 0.5, or 1)', null=True),
        ),
        migrations.AddField(
            model_name='dailyagenda',
            name='target_3_score',
            field=models.FloatField(blank=True, help_text='Score for target 3 (0, 0.5, or 1)', null=True),
        ),
    ]
