# Generated by Django 4.2.25 on 2025-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_dailyagenda_target_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyagenda',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-form notes for the day (supports Markdown)', null=True),
        ),
    ]
