# Generated by Django 4.2.25 on 2025-10-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_dailyagenda_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyagenda',
            name='day_score',
            field=models.FloatField(blank=True, help_text='Overall score for the day (0.0 to 1.0, calculated from target scores)', null=True),
        ),
    ]
