# Generated by Django 4.2.25 on 2025-10-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_dailyagenda_day_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_1',
            field=models.CharField(blank=True, help_text='Target 1 text', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_2',
            field=models.CharField(blank=True, help_text='Target 2 text', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_3',
            field=models.CharField(blank=True, help_text='Target 3 text', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
