# Generated by Django 4.2.25 on 2025-10-29 13:18

from django.db import migrations
import re


def clean_target_timestamps(apps, schema_editor):
    """
    Remove timestamp suffixes from target text fields.

    When migrating from Target ForeignKeys to CharField, Django stored
    the target_id (which had format: "text_1234567890.123456").
    This migration strips the timestamp suffix to leave just the text.
    """
    DailyAgenda = apps.get_model('targets', 'DailyAgenda')

    # Pattern to match: underscore + unix timestamp + optional decimal
    # Example: "_1761707834.477718" or "_1761707834"
    timestamp_pattern = re.compile(r'_\d{10}(?:\.\d+)?$')

    updated_count = 0

    for agenda in DailyAgenda.objects.all():
        changed = False

        # Clean target_1
        if agenda.target_1 and timestamp_pattern.search(agenda.target_1):
            agenda.target_1 = timestamp_pattern.sub('', agenda.target_1)
            changed = True

        # Clean target_2
        if agenda.target_2 and timestamp_pattern.search(agenda.target_2):
            agenda.target_2 = timestamp_pattern.sub('', agenda.target_2)
            changed = True

        # Clean target_3
        if agenda.target_3 and timestamp_pattern.search(agenda.target_3):
            agenda.target_3 = timestamp_pattern.sub('', agenda.target_3)
            changed = True

        if changed:
            agenda.save()
            updated_count += 1

    if updated_count > 0:
        print(f"Cleaned timestamps from {updated_count} agenda(s)")


def reverse_clean(apps, schema_editor):
    """Cannot reverse this migration - timestamps are lost."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_alter_dailyagenda_target_1_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_target_timestamps, reverse_clean),
    ]
