# Generated by Django 4.2.25 on 2025-10-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0008_clean_target_timestamps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyagenda',
            old_name='notes',
            new_name='other_plans',
        ),
    ]
