# Generated by Django 4.2.25 on 2025-10-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_remove_dailyagenda_notes_dailyagenda_other_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyagenda',
            name='other_plans_score',
            field=models.FloatField(blank=True, help_text='Score for other plans (0, 0.5, or 1)', null=True),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='other_plans',
            field=models.TextField(blank=True, help_text='Other plans or notes for the day (supports Markdown)', null=True),
        ),
    ]
