# Generated by Django 4.2.27 on 2026-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0012_recalculate_day_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyagenda',
            name='other_plans',
            field=models.TextField(blank=True, default='', help_text='Other plans or notes for the day (supports Markdown)'),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_1',
            field=models.CharField(blank=True, default='', help_text='Target 1 text', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_2',
            field=models.CharField(blank=True, default='', help_text='Target 2 text', max_length=255),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='target_3',
            field=models.CharField(blank=True, default='', help_text='Target 3 text', max_length=255),
        ),
    ]
