# Generated by Django 5.2.7 on 2025-10-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeighIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the weight data (e.g., 'Whoop', 'Manual', 'Withings')",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID from the external source system",
                        max_length=255,
                    ),
                ),
                (
                    "measurement_time",
                    models.DateTimeField(
                        help_text="When the weight measurement was taken"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in pounds (lbs)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weigh-in",
                "verbose_name_plural": "Weigh-ins",
                "ordering": ["-measurement_time"],
                "indexes": [
                    models.Index(
                        fields=["-measurement_time"],
                        name="weight_weig_measure_840ab3_idx",
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="weight_weig_source_67ceab_idx",
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
