# Generated by Django 4.2.25 on 2025-10-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("withings", "Withings"), ("whoop", "Whoop")],
                        help_text="Name of the external service (e.g., 'withings', 'whoop')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        help_text="OAuth access token for API authentication"
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        help_text="OAuth refresh token for obtaining new access tokens"
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OAuth Credential",
                "verbose_name_plural": "OAuth Credentials",
            },
        ),
    ]
