# Generated by Django 4.2.25 on 2025-10-26 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('weight', '0003_remove_oauthcredential'),
    ]
    operations = [
        migrations.DeleteModel(
            name='OAuthCredential',
        ),
    ]
