# Generated by Django 4.2.27 on 2026-02-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_oauthcredential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthCredential',
        ),
    ]
