# Generated by Django 4.2.25 on 2025-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OAuthCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="OAuth provider name (e.g., 'whoop', 'withings')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        help_text="OAuth client ID from the provider", max_length=255
                    ),
                ),
                (
                    "client_secret",
                    models.CharField(
                        help_text="OAuth client secret from the provider",
                        max_length=255,
                    ),
                ),
                (
                    "redirect_uri",
                    models.CharField(
                        help_text="OAuth redirect URI for callback", max_length=500
                    ),
                ),
                (
                    "access_token",
                    models.TextField(
                        blank=True, help_text="Current access token", null=True
                    ),
                ),
                (
                    "refresh_token",
                    models.TextField(
                        blank=True,
                        help_text="Refresh token for obtaining new access tokens",
                        null=True,
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the access token expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OAuth Credential",
                "verbose_name_plural": "OAuth Credentials",
                "ordering": ["provider"],
            },
        ),
    ]
