# Generated by Django 4.2.25 on 2025-10-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text="API provider name (e.g., 'toggl')", max_length=50, unique=True)),
                ('api_token', models.CharField(help_text='API token/key for authentication', max_length=500)),
                ('workspace_id', models.CharField(blank=True, help_text='Workspace/organization ID (if applicable)', max_length=100, null=True)),
                ('api_url', models.CharField(blank=True, help_text='Base API URL (if different from default)', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional provider-specific metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Credential',
                'verbose_name_plural': 'API Credentials',
                'ordering': ['provider'],
            },
        ),
    ]
