# Generated by Django 4.2.27 on 2026-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_integration', '0002_apicredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicredential',
            name='api_url',
            field=models.CharField(blank=True, default='', help_text='Base API URL (if different from default)', max_length=500),
        ),
        migrations.AlterField(
            model_name='apicredential',
            name='workspace_id',
            field=models.CharField(blank=True, default='', help_text='Workspace/organization ID (if applicable)', max_length=100),
        ),
        migrations.AlterField(
            model_name='oauthcredential',
            name='access_token',
            field=models.TextField(blank=True, default='', help_text='Current access token'),
        ),
        migrations.AlterField(
            model_name='oauthcredential',
            name='refresh_token',
            field=models.TextField(blank=True, default='', help_text='Refresh token for obtaining new access tokens'),
        ),
    ]
