# Generated by Django 4.2.25 on 2025-10-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='First day of the month for this objective')),
                ('end', models.DateField(db_index=True, help_text='Last day of the month for this objective')),
                ('label', models.CharField(help_text="Name/description of the objective (e.g., '30 Running Workouts')", max_length=255)),
                ('objective_value', models.FloatField(help_text="Target value for this objective (e.g., 30 for '30 running workouts')")),
                ('objective_definition', models.TextField(help_text='SQL query that defines how to measure this objective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Objective',
                'verbose_name_plural': 'Monthly Objectives',
                'ordering': ['-start', 'label'],
            },
        ),
    ]
