# Generated by Django 4.2.25 on 2025-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='objective_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier for this objective', max_length=255, null=True, unique=True),
        ),
    ]
