# Generated by Django 4.2.25 on 2025-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0002_monthlyobjective_objective_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='timezone',
            field=models.CharField(default='America/Chicago', help_text="Timezone for date range (e.g., 'America/Chicago', 'America/New_York')", max_length=50),
        ),
    ]
