# Generated by Django 4.2.25 on 2025-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0004_monthlyobjective_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='category',
            field=models.CharField(blank=True, help_text="Category for this objective (e.g., 'Nutrition', 'Weight', 'Exercise', 'Time Management')", max_length=50, null=True),
        ),
    ]
