# Generated by Django 4.2.25 on 2025-10-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0005_monthlyobjective_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='description',
            field=models.TextField(blank=True, help_text="Detailed, quantitative description of the objective (e.g., '13 Weigh-In Days')", null=True),
        ),
    ]
