# Generated by Django 4.2.25 on 2025-10-29 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0006_monthlyobjective_description'),
    ]

    operations = [
    ]
