# Generated by Django 4.2.25 on 2025-10-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0007_add_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='unit_of_measurement',
            field=models.CharField(blank=True, help_text="Unit of measurement for this objective (e.g., 'minutes', 'sessions', 'days', 'pounds')", max_length=50, null=True),
        ),
    ]
