# Generated by Django 4.2.25 on 2025-11-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0008_monthlyobjective_unit_of_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyobjective',
            name='historical_display',
            field=models.TextField(blank=True, help_text='SQL query or definition for displaying historical entries in the detail modal', null=True),
        ),
    ]
