# Generated by Django 4.2.27 on 2026-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_objectives', '0009_monthlyobjective_historical_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyobjective',
            name='category',
            field=models.CharField(blank=True, default='', help_text="Category for this objective (e.g., 'Nutrition', 'Weight', 'Exercise', 'Time Management')", max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyobjective',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Detailed, quantitative description of the objective (e.g., '13 Weigh-In Days')"),
        ),
        migrations.AlterField(
            model_name='monthlyobjective',
            name='historical_display',
            field=models.TextField(blank=True, default='', help_text='SQL query or definition for displaying historical entries in the detail modal'),
        ),
        migrations.AlterField(
            model_name='monthlyobjective',
            name='objective_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique identifier for this objective', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='monthlyobjective',
            name='unit_of_measurement',
            field=models.CharField(blank=True, default='', help_text="Unit of measurement for this objective (e.g., 'minutes', 'sessions', 'days', 'pounds')", max_length=50),
        ),
    ]
