# Generated by Django 4.2.26 on 2025-12-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaistMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source of the measurement (e.g., 'Manual', 'App Name')", max_length=50)),
                ('measurement_time', models.DateTimeField(db_index=True, help_text='Date and time when the measurement was taken')),
                ('waist_circumference', models.DecimalField(decimal_places=2, help_text='Waist circumference in inches', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waist Measurement',
                'verbose_name_plural': 'Waist Measurements',
                'db_table': 'waist_measurements_waistmeasurement',
                'ordering': ['-measurement_time'],
            },
        ),
    ]
