# Generated by Django 4.2.26 on 2025-12-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waist_measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaistCircumferenceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source of the measurement (e.g., 'Manual', 'App Name')", max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='ID from external source', max_length=255)),
                ('log_date', models.DateField(db_index=True, help_text='Date when the measurement was taken')),
                ('measurement', models.DecimalField(decimal_places=2, help_text='Waist circumference in inches', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waist Circumference Measurement',
                'verbose_name_plural': 'Waist Circumference Measurements',
                'db_table': 'waist_circumference_measurements',
                'ordering': ['-log_date'],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.DeleteModel(
            name='WaistMeasurement',
        ),
    ]
