# Generated by Django 4.2.27 on 2026-02-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0002_add_source_field'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_start_ae3ff8_idx',
            old_name='calendar_ev_start_c25c7f_idx',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
