# Generated by Django 4.2.27 on 2026-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0003_add_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='override_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='override_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
