# Generated by Django 4.2.25 on 2025-10-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.AutoField(
                        help_text="Unique project identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_string",
                    models.CharField(
                        help_text="Human-readable project name", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["display_string"],
            },
        ),
    ]
