# Generated by Django 4.2.25 on 2025-10-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0004_delete_whoopsportid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoopSportId',
            fields=[
                ('sport_id', models.IntegerField(help_text='Whoop sport ID', primary_key=True, serialize=False)),
                ('sport_name', models.CharField(help_text='Name of the sport/activity', max_length=100)),
            ],
            options={
                'verbose_name': 'Whoop Sport ID',
                'verbose_name_plural': 'Whoop Sport IDs',
                'db_table': 'whoop_sport_ids',
                'ordering': ['sport_id'],
            },
        ),
    ]
