# Generated by Django 4.2.25 on 2025-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "goal_id",
                    models.IntegerField(
                        help_text="Unique goal identifier (Toggl Tag ID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display_string",
                    models.CharField(
                        help_text="Human-readable goal name (Toggl Tag name)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ["display_string"],
            },
        ),
    ]
