# Generated by Django 4.2.25 on 2025-10-31 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_convert_goal_names_to_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_id',
            field=models.CharField(help_text='Unique goal identifier (Toggl Tag ID)', max_length=255, primary_key=True, serialize=False),
        ),
    ]
