# Generated by Django 4.2.25 on 2025-10-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Manual",
                        help_text="Source of the time log data (e.g., 'Toggl', 'Manual')",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID from the external source system",
                        max_length=255,
                    ),
                ),
                ("start", models.DateTimeField(help_text="When the time log started")),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the time log ended (null if still in progress)",
                        null=True,
                    ),
                ),
                (
                    "goal_id",
                    models.IntegerField(
                        blank=True, help_text="Associated goal ID", null=True
                    ),
                ),
                (
                    "project_id",
                    models.IntegerField(
                        blank=True, help_text="Associated project ID", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "ordering": ["-start"],
                "indexes": [
                    models.Index(
                        fields=["-start"], name="time_logs_t_start_502eb3_idx"
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="time_logs_t_source_ad0223_idx",
                    ),
                    models.Index(
                        fields=["goal_id"], name="time_logs_t_goal_id_57abe1_idx"
                    ),
                    models.Index(
                        fields=["project_id"], name="time_logs_t_project_d70fcf_idx"
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
