# Generated by Django 4.2.25 on 2025-10-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="source",
            field=models.CharField(
                default="Manual",
                help_text="Source of the time log data (e.g., 'Toggl', 'Manual')",
                max_length=50,
            ),
        ),
    ]
