# Generated by Django 4.2.25 on 2025-11-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WritingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source of the writing log data (e.g., 'Manual', 'Toggl')", max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='ID from the external source system', max_length=255)),
                ('log_date', models.DateField(help_text='Date of the writing session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writing Log',
                'verbose_name_plural': 'Writing Logs',
                'db_table': 'writing_logs',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['-log_date'], name='writing_log_log_dat_9f30d2_idx'), models.Index(fields=['source', 'source_id'], name='writing_log_source_c54a07_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
