# Generated by Django 4.2.25 on 2025-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writinglog',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Duration of writing session in hours', max_digits=4, null=True),
        ),
    ]
