# Generated by Django 4.2.26 on 2025-12-07 19:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_writinglog_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title or name of the image (e.g., 'Bunny', 'Fire')", max_length=100)),
                ('image', cloudinary.models.CloudinaryField(help_text='Image file to display on the writing page', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(help_text='Novel excerpt that appears in the modal when clicking this image')),
                ('order', models.IntegerField(default=0, help_text='Display order on the page (lower numbers appear first)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this image is currently displayed on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Writing Page Image',
                'verbose_name_plural': 'Writing Page Images',
                'ordering': ['order', 'title'],
            },
        ),
    ]
