# Generated by Django 4.2.26 on 2025-12-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_writingpageimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='writingpageimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Writing Page Image', 'verbose_name_plural': 'Writing Page Images'},
        ),
        migrations.RemoveField(
            model_name='writingpageimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='writingpageimage',
            name='title',
        ),
    ]
