# Generated by Django 4.2.26 on 2025-11-29 02:06

from django.db import migrations, models
import inspirations_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations_app', '0003_add_title_make_flip_text_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspiration',
            options={'ordering': ['created_at'], 'verbose_name': 'Inspiration', 'verbose_name_plural': 'Inspirations'},
        ),
        migrations.AddField(
            model_name='inspiration',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube trailer URL (auto-populated for films)', null=True),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='image',
            field=models.ImageField(help_text='Upload an image (book cover, album art, movie poster, etc.)', upload_to=inspirations_app.models.inspiration_image_path),
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='type',
            field=models.CharField(choices=[('Film', 'Film'), ('Book', 'Book'), ('Album', 'Album'), ('TV Show', 'TV Show'), ('Podcast Series', 'Podcast Series'), ('Article', 'Article'), ('Other', 'Other')], help_text='Type of inspiration', max_length=50),
        ),
    ]
