# Generated by Django 4.2.26 on 2025-11-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations_app', '0004_alter_inspiration_options_inspiration_youtube_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspiration',
            old_name='youtube_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='inspiration',
            name='url',
            field=models.URLField(blank=True, help_text='URL link (e.g., trailer, Goodreads, Spotify, etc.)', null=True),
        ),
    ]
