# Generated by Django 4.2.27 on 2026-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspirations_app', '0005_rename_youtube_url_to_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspiration',
            name='url',
            field=models.URLField(blank=True, default='', help_text='URL link (e.g., trailer, Goodreads, Spotify, etc.)'),
        ),
    ]
