# Generated by Django 4.2.25 on 2025-10-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(help_text='Unique identifier for this setting', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(help_text='Value for this setting')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of what this setting controls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
    ]
