# Generated by Django 4.2.25 on 2025-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeTrackerColumn',
            fields=[
                ('column_name', models.CharField(help_text="Internal name of the column (e.g., 'run', 'fast', 'strength')", max_length=50, primary_key=True, serialize=False, unique=True)),
                ('display_name', models.CharField(help_text='Display name shown in the column header', max_length=100)),
                ('tooltip_text', models.TextField(help_text='Help text that appears when hovering over the column header')),
                ('sql_query', models.TextField(help_text='SQL query to determine if checkbox should appear. Available parameters: :day_start, :day_end. Query should return a count.')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this column is currently enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Life Tracker Column',
                'verbose_name_plural': 'Life Tracker Columns',
                'ordering': ['order', 'column_name'],
            },
        ),
    ]
