# Generated by Django 4.2.25 on 2025-11-13 22:45

from django.db import migrations


def populate_defaults(apps, schema_editor):
    LifeTrackerColumn = apps.get_model('settings', 'LifeTrackerColumn')

    columns = [
        {
            'column_name': 'run',
            'display_name': 'Run',
            'tooltip_text': 'Run at least 1 mile every day to maintain cardiovascular fitness and endurance.',
            'sql_query': 'SELECT COUNT(*) FROM workouts_workout WHERE sport_id = 0 AND start >= :day_start AND start <= :day_end',
            'order': 1,
        },
        {
            'column_name': 'fast',
            'display_name': 'Fast',
            'tooltip_text': 'Complete a daily fast to support metabolic health and discipline.',
            'sql_query': 'SELECT COUNT(*) FROM fasting_fastingsession WHERE fast_end_date >= :day_start AND fast_end_date <= :day_end',
            'order': 2,
        },
        {
            'column_name': 'strength',
            'display_name': 'Strength Training',
            'tooltip_text': 'Perform strength training exercises at least three days per week to build muscle and maintain strength.',
            'sql_query': 'SELECT COUNT(*) FROM workouts_workout WHERE sport_id = 48 AND start >= :day_start AND start <= :day_end',
            'order': 3,
        },
        {
            'column_name': 'eat_clean',
            'display_name': 'Eat Clean',
            'tooltip_text': 'Eat clean, whole foods throughout the day to fuel your body and support overall health.',
            'sql_query': 'SELECT CASE WHEN SUM(calories) <= 1500 AND SUM(carbs) <= 100 THEN 1 ELSE 0 END FROM nutrition_nutritionentry WHERE consumption_date >= :day_start AND consumption_date <= :day_end',
            'order': 4,
        },
        {
            'column_name': 'write',
            'display_name': 'Write',
            'tooltip_text': 'Dedicate 2 hours each day to focused writing to develop your craft and create meaningful content.',
            'sql_query': 'SELECT 0',  # Not implemented yet
            'order': 5,
        },
        {
            'column_name': 'weigh_in',
            'display_name': 'Weigh In',
            'tooltip_text': 'Track your weight daily to monitor progress and stay accountable to your health goals.',
            'sql_query': 'SELECT COUNT(*) FROM weight_weighin WHERE measurement_time >= :day_start AND measurement_time <= :day_end',
            'order': 6,
        },
    ]

    for col_data in columns:
        LifeTrackerColumn.objects.create(**col_data)


def reverse_populate(apps, schema_editor):
    LifeTrackerColumn = apps.get_model('settings', 'LifeTrackerColumn')
    LifeTrackerColumn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_lifetrackercolumn'),
    ]

    operations = [
        migrations.RunPython(populate_defaults, reverse_populate),
    ]
