# Generated by Django 4.2.25 on 2025-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_populate_life_tracker_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='details_display',
            field=models.TextField(blank=True, default='', help_text='Text configuration for details shown when hovering over checkmarks'),
        ),
    ]
