# Generated by Django 4.2.26 on 2025-12-18 20:06

from django.db import migrations, models
from datetime import date


def set_default_start_dates(apps, _schema_editor):
    """
    Set start_date = Nov 10, 2025 for all existing enabled habits.
    """
    LifeTrackerColumn = apps.get_model('settings', 'LifeTrackerColumn')
    default_start_date = date(2025, 11, 10)

    # Update all enabled columns
    LifeTrackerColumn.objects.filter(enabled=True).update(start_date=default_start_date)


def reverse_start_dates(apps, _schema_editor):
    """
    Reverse migration: set all start_dates back to NULL.
    """
    LifeTrackerColumn = apps.get_model('settings', 'LifeTrackerColumn')
    LifeTrackerColumn.objects.all().update(start_date=None)


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_lifetrackercolumn_details_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='end_date',
            field=models.CharField(default='ongoing', help_text="Date when this habit ends (YYYY-MM-DD) or 'ongoing'", max_length=20),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when this habit becomes active', null=True),
        ),
        migrations.RunPython(set_default_start_dates, reverse_start_dates),
    ]
