# Generated by Django 4.2.26 on 2025-12-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_add_icon_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent habit (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='settings.lifetrackercolumn'),
        ),
        migrations.AlterField(
            model_name='lifetrackercolumn',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
