# Generated by Django 4.2.26 on 2025-12-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_lifetrackercolumn_parent_alter_lifetrackercolumn_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifetrackercolumn',
            name='enabled',
        ),
    ]
