# Generated by Django 4.2.26 on 2025-12-29 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_remove_lifetrackercolumn_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lifetrackercolumn',
            options={'ordering': ['id'], 'verbose_name': 'Life Tracker Column', 'verbose_name_plural': 'Life Tracker Columns'},
        ),
        migrations.RemoveField(
            model_name='lifetrackercolumn',
            name='order',
        ),
    ]
