# Generated by Django 4.2.26 on 2025-12-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_lifetrackercolumn_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='create_endpoint',
            field=models.CharField(blank=True, default='', help_text="Django URL name for creating records (e.g., 'fasting:log_fast')", max_length=100),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='has_add_button',
            field=models.BooleanField(default=False, help_text='Show + button on hover for empty cells'),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='modal_body_text',
            field=models.TextField(blank=True, default='', help_text='Main text/question shown in modal body'),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='modal_title',
            field=models.CharField(blank=True, default='', help_text='Title shown in the modal header', max_length=100),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='modal_type',
            field=models.CharField(blank=True, choices=[('', 'No modal'), ('simple_confirm', 'Simple Yes/No confirmation'), ('duration_select', 'Duration selection (like fasting)')], default='', help_text='Type of modal to show when + button is clicked', max_length=50),
        ),
    ]
