# Generated by Django 4.2.26 on 2025-12-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_lifetrackercolumn_create_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='modal_input_label',
            field=models.CharField(blank=True, default='', help_text='Label for input field (used with value_input modal type)', max_length=100),
        ),
        migrations.AlterField(
            model_name='lifetrackercolumn',
            name='modal_type',
            field=models.CharField(blank=True, choices=[('', 'No modal'), ('simple_confirm', 'Simple Yes/No confirmation'), ('duration_select', 'Duration selection (like fasting)'), ('value_input', 'Value input (for measurements, etc.)')], default='', help_text='Type of modal to show when + button is clicked', max_length=50),
        ),
    ]
