# Generated by Django 4.2.26 on 2025-12-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_lifetrackercolumn_modal_input_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='total_column_text',
            field=models.CharField(blank=True, default='', help_text="Text shown in Total column on Life Metrics page (e.g., 'days eating clean'). If blank, uses display_name.", max_length=100),
        ),
    ]
