# Generated by Django 4.2.26 on 2026-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_lifetrackercolumn_total_column_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='abandoned_status',
            field=models.JSONField(blank=True, default=dict, help_text="JSON storing abandoned dates: {'2026-01-09': true, '2026-01-10': true}"),
        ),
        migrations.AddField(
            model_name='lifetrackercolumn',
            name='allow_abandon',
            field=models.BooleanField(default=False, help_text='Allow users to mark days as abandoned (shows abandon icon on hover)'),
        ),
    ]
