# Generated by Django 4.2.26 on 2025-12-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAvoidanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source of the log data (e.g., 'Manual', 'API')", max_length=50)),
                ('source_id', models.CharField(db_index=True, help_text='ID from the external source system', max_length=255)),
                ('log_date', models.DateField(help_text='Date of the YouTube avoidance log')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Avoidance Log',
                'verbose_name_plural': 'YouTube Avoidance Logs',
                'db_table': 'youtube_avoidance_logs',
                'ordering': ['-log_date'],
                'indexes': [models.Index(fields=['-log_date'], name='youtube_avo_log_dat_7742fe_idx'), models.Index(fields=['source', 'source_id'], name='youtube_avo_source_5a92d7_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
