# Generated by Django 4.2.27 on 2026-01-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_taskcontext_task_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcontext',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
    ]
