# Generated by Django 4.2.27 on 2026-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_taskstate_alter_taskcontext_color_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
    ]
