# Generated by Django 4.2.27 on 2026-01-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_taskstate_is_terminal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstate',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='taskstate',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
