# Generated by Django 4.2.27 on 2026-01-29 23:44

from django.db import migrations


def create_inbox_state(apps, schema_editor):
    TaskState = apps.get_model('todos', 'TaskState')
    # Create Inbox state if it doesn't exist
    inbox, created = TaskState.objects.get_or_create(
        name='Inbox',
        defaults={'order': 0, 'is_terminal': False}
    )
    if not created:
        # Ensure Inbox has order 0
        inbox.order = 0
        inbox.save()

    # Shift all other non-terminal states to have order >= 1
    TaskState.objects.filter(is_terminal=False).exclude(name='Inbox').update(order=models.F('order') + 1)


def create_inbox_state_fixed(apps, schema_editor):
    TaskState = apps.get_model('todos', 'TaskState')
    Task = apps.get_model('todos', 'Task')

    # Create Inbox state if it doesn't exist
    inbox, created = TaskState.objects.get_or_create(
        name='Inbox',
        defaults={'order': 0, 'is_terminal': False}
    )
    if not created:
        # Ensure Inbox has order 0
        inbox.order = 0
        inbox.save()

    # Shift all other non-terminal states to have order >= 1
    for state in TaskState.objects.filter(is_terminal=False).exclude(name='Inbox'):
        state.order = state.order + 1
        state.save()

    # Assign existing tasks without a state to Inbox
    Task.objects.filter(state__isnull=True).update(state=inbox)


def reverse_inbox_state(apps, schema_editor):
    # Don't delete Inbox on reverse - just leave it
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_alter_taskstate_options_taskstate_order'),
    ]

    operations = [
        migrations.RunPython(create_inbox_state_fixed, reverse_inbox_state),
    ]
