# Generated by Django 4.2.27 on 2026-01-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_add_inbox_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='bootstrap_icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
