# Generated by Django 4.2.27 on 2026-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_add_bootstrap_icon_to_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
