# Generated by Django 4.2.26 on 2026-01-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_add_order_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='today',
            field=models.BooleanField(default=False),
        ),
    ]
