# Generated by Django 4.2.26 on 2026-01-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_task_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='section_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_period',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
