# Generated by Django 4.2.27 on 2026-01-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_task_section_number_task_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='context',
        ),
        migrations.RemoveField(
            model_name='task',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='task',
            name='time_period',
        ),
        migrations.RemoveField(
            model_name='task',
            name='today',
        ),
    ]
