# Generated by Django 4.2.27 on 2026-01-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_remove_unused_task_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskContext',
        ),
        migrations.RemoveField(
            model_name='taskstate',
            name='is_terminal',
        ),
    ]
