# Generated by Django 4.2.27 on 2026-01-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0015_add_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
