# Generated by Django 4.2.26 on 2026-01-31 14:09

from django.db import migrations


def migrate_calendar_times_to_schedules(apps, schema_editor):
    """Migrate existing calendar_start_time/end_time to TaskSchedule records."""
    Task = apps.get_model('todos', 'Task')
    TaskSchedule = apps.get_model('todos', 'TaskSchedule')

    tasks_with_calendar = Task.objects.filter(calendar_start_time__isnull=False)

    for task in tasks_with_calendar:
        # Create a TaskSchedule for each task that has calendar times
        TaskSchedule.objects.create(
            task=task,
            start_time=task.calendar_start_time,
            end_time=task.calendar_end_time or task.calendar_start_time
        )


def reverse_migration(apps, schema_editor):
    """Reverse the migration by clearing TaskSchedule records."""
    TaskSchedule = apps.get_model('todos', 'TaskSchedule')
    TaskSchedule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0019_taskschedule'),
    ]

    operations = [
        migrations.RunPython(migrate_calendar_times_to_schedules, reverse_migration),
    ]
