# Generated by Django 4.2.27 on 2026-01-31 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0020_migrate_calendar_times_to_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='calendar_end_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='calendar_start_time',
        ),
    ]
