# Generated by Django 4.2.27 on 2026-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0023_taskview'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
