# Generated by Django 4.2.27 on 2026-01-31 22:03

from django.db import migrations, models


def set_default_state_changed_at(apps, schema_editor):
    """Set state_changed_at to created_at for all existing tasks."""
    Task = apps.get_model('todos', 'Task')
    for task in Task.objects.filter(state_changed_at__isnull=True):
        task.state_changed_at = task.created_at
        task.save(update_fields=['state_changed_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0024_add_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstate',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_default_state_changed_at, migrations.RunPython.noop),
    ]
