# Generated by Django 4.2.27 on 2026-01-31 23:02

from django.db import migrations, models


def set_default_terminal_state(apps, _schema_editor):
    """Set the last non-system state as terminal if no terminal state exists."""
    TaskState = apps.get_model('todos', 'TaskState')
    # Get the last non-system state by order
    last_state = TaskState.objects.filter(is_system=False).order_by('-order').first()
    if last_state:
        last_state.is_terminal = True
        last_state.save(update_fields=['is_terminal'])


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0025_add_abandoned_task_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='is_terminal',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_default_terminal_state, migrations.RunPython.noop),
    ]
