# Generated by Django 4.2.27 on 2026-02-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0026_add_terminal_state_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_for_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
