# Generated by Django 4.2.26 on 2026-02-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0027_add_done_for_day_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
