# Generated by Django 4.2.27 on 2026-02-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0028_task_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstate',
            name='show_priority_indicator',
            field=models.BooleanField(default=False),
        ),
    ]
