# Generated by Django 4.2.26 on 2026-02-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0028_task_starred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='starred',
        ),
    ]
