# Generated by Django 4.2.27 on 2026-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0029_taskstate_show_priority_indicator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstate',
            old_name='show_priority_indicator',
            new_name='show_signal_noise',
        ),
        migrations.AddField(
            model_name='task',
            name='is_signal',
            field=models.BooleanField(default=False),
        ),
    ]
