# Generated by Django 4.2.27 on 2026-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0030_rename_show_priority_indicator_taskstate_show_signal_noise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='signal_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
