# Generated by Django 4.2.26 on 2026-02-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0029_remove_task_starred'),
        ('todos', '0031_task_signal_slot'),
    ]

    operations = [
    ]
