# Generated by Django 4.2.26 on 2026-02-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0032_merge_0029_remove_task_starred_0031_task_signal_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='noise_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
