# Generated by Django 4.2.26 on 2026-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0033_task_noise_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='time_blocks', to='todos.task'),
        ),
    ]
