# Generated by Django 4.2.26 on 2026-02-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0034_timeblock_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='task_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
