# Generated by Django 4.2.25 on 2025-10-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NutritionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the nutrition data (e.g., 'Manual', 'MyFitnessPal')",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID from the external source system",
                        max_length=255,
                    ),
                ),
                (
                    "consumption_date",
                    models.DateTimeField(
                        help_text="When the food was consumed (local datetime)"
                    ),
                ),
                (
                    "calories",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total calories consumed",
                        max_digits=7,
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=2, help_text="Fat in grams", max_digits=6
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Carbohydrates in grams",
                        max_digits=6,
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2, help_text="Protein in grams", max_digits=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Nutrition Entry",
                "verbose_name_plural": "Nutrition Entries",
                "ordering": ["-consumption_date"],
                "indexes": [
                    models.Index(
                        fields=["-consumption_date"],
                        name="nutrition_n_consump_1ffe0c_idx",
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="nutrition_n_source_1a205c_idx",
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
