# Generated by Django 4.2.25 on 2025-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionentry',
            name='abandoned',
            field=models.BooleanField(default=False, help_text='True if user stopped tracking nutrition for this day'),
        ),
    ]
