# Generated by Django 4.2.25 on 2025-10-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FastingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the fasting data (e.g., 'Zero', 'Manual')",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID from the external source system",
                        max_length=255,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fasting duration in hours",
                        max_digits=5,
                    ),
                ),
                (
                    "fast_end_date",
                    models.DateTimeField(help_text="When the fast ended (UTC)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fasting Session",
                "verbose_name_plural": "Fasting Sessions",
                "ordering": ["-fast_end_date"],
                "indexes": [
                    models.Index(
                        fields=["-fast_end_date"], name="fasting_fas_fast_en_8c3909_idx"
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="fasting_fas_source_86ea31_idx",
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
