# Generated by Django 5.2.7 on 2025-10-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of the workout data (e.g., 'Whoop', 'Manual')",
                        max_length=50,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        help_text="ID from the external source system",
                        max_length=255,
                    ),
                ),
                ("start", models.DateTimeField(help_text="Workout start time")),
                ("end", models.DateTimeField(help_text="Workout end time")),
                (
                    "timezone_offset",
                    models.CharField(
                        help_text="Timezone offset (e.g., '+00:00')", max_length=10
                    ),
                ),
                ("sport_id", models.IntegerField(help_text="Sport/activity type ID")),
                (
                    "average_heart_rate",
                    models.IntegerField(
                        blank=True,
                        help_text="Average heart rate during workout (bpm)",
                        null=True,
                    ),
                ),
                (
                    "max_heart_rate",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum heart rate during workout (bpm)",
                        null=True,
                    ),
                ),
                (
                    "calories_burned",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total calories burned during workout",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start"],
                "indexes": [
                    models.Index(
                        fields=["-start"], name="workouts_wo_start_15b314_idx"
                    ),
                    models.Index(
                        fields=["source", "source_id"],
                        name="workouts_wo_source_15fd0a_idx",
                    ),
                ],
                "unique_together": {("source", "source_id")},
            },
        ),
    ]
