# Generated by Django 4.2.25 on 2025-10-28 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_whoopsportid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WhoopSportId',
        ),
    ]
