# Generated by Django 4.2.25 on 2025-10-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_delete_whoopsportid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='distance_in_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance covered in miles (for applicable sports)', max_digits=8, null=True),
        ),
    ]
